2014/06/24 09:54:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=gii
---
2014/06/24 09:54:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=gii
---
2014/06/25 01:16:29 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:16:52 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.photo' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `photo`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:17:35 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:17:38 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:17:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:21:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `User`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:22:16 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:22:19 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:22:27 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:35:24 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:36:01 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:36:22 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php (13)
2014/06/25 01:50:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user.admin".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user.admin')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user.admin
---
2014/06/25 01:51:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/login
---
2014/06/25 01:51:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
---
2014/06/25 01:51:40 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=user/index
---
2014/06/25 01:51:50 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=user
---
2014/06/25 01:53:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
---
2014/06/25 01:53:46 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=user
---
2014/06/25 01:55:01 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=user/view&id=1
---
2014/06/25 01:56:00 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=user/index
---
2014/06/25 01:56:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('admin')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=admin
---
2014/06/25 01:57:05 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/admin
---
2014/06/25 02:04:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "amdin".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('amdin')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('amdin')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/amdin')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=user/amdin
---
2014/06/25 04:56:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/contact
---
2014/06/25 04:56:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php
---
2014/06/25 04:56:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/contact
---
2014/06/25 05:01:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "phôt".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('ph??t')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=ph%C3%B4t
---
2014/06/25 05:02:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=photo/view&id=1
---
2014/06/25 05:02:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=photo
---
2014/06/25 05:02:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/photo
---
2014/06/25 05:02:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/photo
---
2014/06/25 05:03:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/photo
---
2014/06/25 05:03:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/photo
---
2014/06/25 05:03:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "photo".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('photo')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/photo')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/photo
---
2014/06/26 06:48:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/contact
---
2014/06/26 06:48:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/page&view=photo
---
2014/06/26 06:48:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/page&view=photo
---
2014/06/26 06:49:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/page&view=photo
---
2014/06/26 06:49:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/page&view=photo
---
2014/06/26 06:49:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/page&view=photo
---
2014/06/26 06:49:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "photo" was not found.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php:112
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CViewAction.php(123): CViewAction->resolveView('photo')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CAction.php(76): CViewAction->run()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CAction->runWithParams(Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CViewAction))
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/TheFirstApp/index.php?r=site/page&view=photo
HTTP_REFERER=http://localhost/TheFirstApp/index.php?r=site/page&view=photo
---
2014/06/26 06:50:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('admin')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=admin
---
2014/06/26 06:51:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fii".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('fii')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=fii
---
2014/06/26 06:55:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "post".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('post')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=post
---
2014/06/27 00:46:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/admin".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/admin')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=gii/admin
---
2014/06/27 00:47:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "about".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('about')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=about
---
2014/06/27 00:49:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('admin')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=admin
---
2014/06/27 01:05:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "usercontroller".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('usercontroller')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=usercontroller
---
2014/06/27 01:05:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Usercontroller".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('Usercontroller')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /Applications/XAMPP/xamppfiles/htdocs/TheFirstApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/TheFirstApp/index.php?r=Usercontroller
---
